### ISSUE TITLE
Integrate with Hyperledger Caliper

### ISSUE THREAD

**Issue by levanthanh3005** [hyperledger-labs/convector#118]
Hello,
After building smart contract, I would like to test benmark with the contract with Hyperledger Caliper.
However I have some troubles with config files,
Is there any guides or any generator could support that ?
Thank you

**Comment by diestrin** [comment]
Hi. Caliper is a tool for networks, not contracts. So it has more to do with [Hurley](https://github.com/worldsibu/hurley) than with Convector itself.

Having said that, me as a maintainer of both, I haven't test Caliper with Hurley, I tried Caliper once in a self generated network and it didn't work at that time, so I didn't spend too much time on it.

If you have a specific problem with Hurley and Caliper, open an issue in Hurley's repo with more information to check what the problem is.
